### PR TITLE
[RFC] Hook RedisOplog into the core

### LINKED ISSUE #205: Overwriting OplogHandle
@theodorDiaconu Have you ever considered overwriting OplogHandle class from Meteor's `mongo` package? 

https://github.com/meteor/meteor/blob/d93c021c896029d774ccecc7241ff20ec4045568/packages/mongo/oplog_tailing.js

I had a quick look and it seems like all the logic specific to mongo oplog tailing is already abstracted to this class.

It might be an interesting alternative to make the package smaller and more tightly bound with observer mechanisms in Meteor core.

I'd be interested to hear your thoughts on this matter.

### LINKED ISSUE #276: Removed nonexistent document errors when using server side autorun
See [sample reproduction repo](https://github.com/etyp/redis-autorun-issue). Happens 100% of the time.

Related to https://github.com/cult-of-coders/redis-oplog/issues/145 https://github.com/cult-of-coders/redis-oplog/issues/89 https://github.com/cult-of-coders/redis-oplog/issues/122

## Context
If you subscribe to 2 different publications that return the same document, where 1 publication uses a server side autorun from [peerlibrary:server-autorun](https://github.com/peerlibrary/meteor-server-autorun) or [peerlibrary:reactive-publish](https://github.com/peerlibrary/meteor-reactive-publish) which does multiple `find`s of the same document, you'll receive an error when the item is removed from the publication:

```
I20180421-15:12:21.802(-4)? Exception in callback of async function: Error: Removed nonexistent document dEKXyFJdbn9DYA7Sf
I20180421-15:12:21.803(-4)?     at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
I20180421-15:12:21.803(-4)?     at Session.removed (packages/ddp-server/livedata_server.js:394:10)
I20180421-15:12:21.803(-4)?     at Subscription.removed (packages/ddp-server/livedata_server.js:1292:19)
I20180421-15:12:21.803(-4)?     at Object.removed (packages/mongo/collection.js:368:13)
I20180421-15:12:21.803(-4)?     at Object.removed (packages/cultofcoders:redis-oplog/lib/mongo/extendObserveChanges.js:100:26)
I20180421-15:12:21.803(-4)?     at currentObservers.forEach.observer (packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:141:38)
I20180421-15:12:21.804(-4)?     at Array.forEach (<anonymous>)
I20180421-15:12:21.804(-4)?     at PublicationEntry.send (packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:140:34)
I20180421-15:12:21.804(-4)?     at ObservableCollection.send (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:163:23)
I20180421-15:12:21.804(-4)?     at ObservableCollection.remove (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:253:18)
I20180421-15:12:21.804(-4)?     at handleUpdate (packages/cultofcoders:redis-oplog/lib/processors/direct.js:51:34)
I20180421-15:12:21.804(-4)?     at packages/cultofcoders:redis-oplog/lib/processors/direct.js:12:13
I20180421-15:12:21.805(-4)?     at RedisSubscriber.process (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriber.js:51:24)
I20180421-15:12:21.805(-4)?     at subscribers.forEach.redisSubscriber (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriptionManager.js:143:33)
I20180421-15:12:21.805(-4)?     at Array.forEach (<anonymous>)
I20180421-15:12:21.805(-4)?     at RedisSubscriptionManager.process (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriptionManager.js:142:25)
I20180421-15:12:21.805(-4)?     at events.forEach.event (packages/cultofcoders:redis-oplog/lib/mongo/lib/dispatchers.js:28:42)
I20180421-15:12:21.805(-4)?     at Array.forEach (<anonymous>)
I20180421-15:12:21.806(-4)?     at RedisSubscriptionManager.queue.queueTask.Meteor.bindEnvironment (packages/cultofcoders:redis-oplog/lib/mongo/lib/dispatchers.js:22:22)
I20180421-15:12:21.806(-4)?     at runWithEnvironment (packages/meteor.js:1238:24)
I20180421-15:12:21.806(-4)?     at Object.task (packages/meteor.js:1251:14)
I20180421-15:12:21.806(-4)?     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:869:16)
```

The code to cause this is pretty straightforward:

```
Meteor.publish('allItems', function allItemsPublish() {
  return Items.find({ deleted: false });
});

Meteor.publish('singleItem', function singleItemPublish() {
  const pub = this;

  pub.autorun(() => {
    // The `findOne` below causes the error to throw.
    const item = Items.findOne(defaultItem._id);
    // Would usually run some logic on `item` here using collection helpers
    // and use that to decide what else or what fields we'd want to publish.
    return Items.find({ _id: defaultItem._id, deleted: false });
  });
});
```

## Why this matters/is a problem
This example is contrived, but our codebase has tons of logic that uses server side autoruns like this to do things like:

- Use collection helpers to decide what fields will/will not show for a given user (permissions type stuff)
- Use document data to decide if we want to publish additional cursors from other collections (list views vs detail views)

### LINKED ISSUE #281: ServerSide Autorun Triggers 'Removed' Events Bug
We use serverside autoruns pretty heavily in our codebase. Upon adding a new user to our workspace model we sometimes see all the existing users get removed from the client side collection. This does not happen every time so that leads me to believe there is a race condition that is causing this. Looking at the ddp messages sent through websocket, I noticed that the server is actually sending 'removed' events down to the client. I was not able to reproduce this exactly in this simple repo but I think I was able to get at the core of the problem.

Here is a simple reproduction repo:
https://github.com/hiveteams/redis-oplog-reproduction

## Issue
When changes to the workspace document are made (ex: a new user being added to the list of workspace members), the redis oplog causes removed events to be propagated to the client resulting in users disappearing from the client collection.

## Steps to reproduce
1. Run `meteor npm i`
2. Start the server with `npm start`
3. Load localhost:3000
4. Make sure redis oplog is enabled
5. Click to add 100 users (might have to do this more than once)
6. Notice that the users are not cleanly added, several 'removed' events are sent through ddp.

If you toggle to disable redis oplog and then try again you will notice that no 'removed' events are sent through ddp.

## Workspace
```json
{
  "_id": "Mongo id",
  "members": "List of user ids"
}
```

## User
```json
{
  "_id": "Mongo id"
}
```

## The Code

Basically just a publish where we depend on the results of the workspaces query to return the final set of users:

```javascript
Meteor.publish('allUsers', function allUsersPub(enableRedisOplog) {
  this.autorun(() => {
    // listen to changes in the workspace document
    const workspace = Workspaces.find().fetch()[0];

    // optionally disable redis oplog
    const options = {};
    if (!enableRedisOplog) {
      options.disableOplog = true;
    }

    // return users cursor
    return Users.find({
      _id: { $in: workspace.members }
    }, options);
  });
});
```

### LINKED ISSUE #284: Missing mutations event if Mongo collection changes while performing initial add
If updates to the mongo collection occur while adding initial values to the observer, those changes are missed. 

I found out, by reading the debug logs, that the channel subscription is being queued and only runs after the addition of initial values, leading to missed messages from redis.

I was able to fix it with the following changes:
```js
// RedisSubscriptionManager.js
...
    attach(redisSubscriber) {
        this.queue.queueTask(() => {
            _.each(redisSubscriber.channels, channel => {
                if (!this.store[channel]) {
                    this.initializeChannel(channel);
                }

                this.store[channel].push(redisSubscriber);
            });
        });
    }
...
```
to:
```js
// RedisSubscriptionManager.js
...
    attach(redisSubscriber) {
        _.each(redisSubscriber.channels, channel => {
            if (!this.store[channel]) {
                this.initializeChannel(channel);
            }

            this.store[channel].push(redisSubscriber);
        });
    }
...
```

This way, the observer is immediately subscribed to the channel and doesn't miss any updates.

All tests passed. Can I send a PR?

Thanks.

### PR DESCRIPTION
**Pull request by theodorDiaconu**
- [x] Fixes #281
- [x] Fixes #284 
- [x] Fixes #276
- [x] Fixes #205 
- [ ] Possible regression #229 ?

### CODE REVIEW

**Comment by ramezrafla** [comment]
I still got removed non-existent doc error, had to change ```ObserverMultiplex``` at line 217

From 
```
                callback && callback.apply(null, EJSON.clone(args));
```
to
```
                if (callback)
                  try { callback.apply(null, EJSON.clone(args)) }
                  catch(e) { }
```

**Comment by theodorDiaconu** [comment]
@ramezrafla as you seen, a reproduction is the fastest way for me to solve the problem. Try to work on that. Also that's strange because we are already silencing out that exception. Are you sure that's the issue ?

**Comment by ramezrafla** [comment]
Hi @theodorDiaconu 

Sorry for delay, GH didn't send me an email from this thread (Grr) even if I am subscribed.
Got it - waiting for it to happen again consistently and will reproduce it

I noticed in https://github.com/cult-of-coders/redis-oplog/blob/patch/276/lib/mongo/ObserveMultiplex.js#L219 that callback would be called twice for "removed" event. Once in the try and once right after.

Is there a reason for that?

**Comment by elm2178** [comment]
Hey @theodorDiaconu 

I am now getting a strange error on startup that I had not seen previously on this branch:

```
TypeError: Cannot read property '_redisOplog' of undefined
W20180504-17:43:17.847(0)? (STDERR)     at new ObservableCollection (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:41:29)
W20180504-17:43:17.863(0)? (STDERR)     at new RedisOplogObserveDriver (packages/cultofcoders:redis-oplog/lib/mongo/RedisOplogObserveDriver.js:29:37)
W20180504-17:43:17.864(0)? (STDERR)     at MongoConnection.<anonymous> (packages/cultofcoders:redis-oplog/lib/mongo/observeChanges.js:120:25)
W20180504-17:43:17.864(0)? (STDERR)     at MongoConnection.MongoInternals.Connection._observeChanges (packages/peerlibrary_reactive-publish/server.coffee:50:35)
W20180504-17:43:17.864(0)? (STDERR)     at MongoConnection.mongoConnectionProto._observeChanges (packages/hiveteams_hive-apm.js:3075:38)
W20180504-17:43:17.864(0)? (STDERR)     at Cursor.observeChanges (packages/mongo/mongo_driver.js:936:22)
W20180504-17:43:17.865(0)? (STDERR)     at Cursor.MeteorCursor.observeChanges (packages/peerlibrary_reactive-mongo/server.coffee:37:35)
W20180504-17:43:17.865(0)? (STDERR)     at Cursor.cursorProto.(anonymous function) (packages/hiveteams_hive-apm.js:3380:32)
W20180504-17:43:17.865(0)? (STDERR)     at Cursor.kadira_Cursor_observeChanges [as observeChanges] (packages/hiveteams_hive-apm.js:3784:41)
W20180504-17:43:17.865(0)? (STDERR)     at Object.startObserveForDeletedServers (packages/konecty_user-presence.js:123:63)
W20180504-17:43:17.866(0)? (STDERR)     at Object.start (packages/konecty_user-presence.js:275:17)
```

We use konecty_user-presence in our app and looking at their source code there isn't anything strange. The line of code that causes this is just an observeChanges
https://github.com/Konecty/meteor-user-presence/blob/72a1ed9af27c6dbd47d22e6ec45481d822db0d2e/server/server.js#L81

Let me know if you need a reproduction for this one, it seems like it wouldn't be too hard to create one.

**Comment by theodorDiaconu** [comment]
@elm2178 the reason that error happens is that when observer starts, it tries to get a collection using _getCollectionByName, and it couldn't find it. In our case is https://github.com/Konecty/meteor-multiple-instances-status/blob/master/multiple-instances-status.js this collection here.

Very weird why it could not find it. Maybe something overrides the mongo prototype ?

**Comment by elm2178** [comment]
@theodorDiaconu I was able to get past the initial issues by reordering my packages so that all peerlibrary packages were added immediately after redis-oplog. I am still not sure why this only happens on this branch and not the master branch of redis-oplog.

Now I am seeing a few new errors that I have not seen before.
1. On startup I am seeing an error from init.js
```
Exception in callback of async function: TypeError: Cannot read property 'forEach' of undefined
I20180507-17:54:47.107(0)?     at onConnect (packages/cultofcoders:redis-oplog/lib/init.js:33:13)
I20180507-17:54:47.107(0)?     at packages/cultofcoders:redis-oplog/lib/redis/getRedisClient.js:55:17
I20180507-17:54:47.107(0)?     at runWithEnvironment (packages/meteor.js:1238:24)
```

2. On sending two messages in quick succession I am seeing
```
Exception from task: Error: Got changed during initial adds
I20180507-17:56:11.496(0)?     at packages/cultofcoders:redis-oplog/lib/mongo/ObserveMultiplex.js:204:23
I20180507-17:56:11.497(0)?     at runWithEnvironment (packages/meteor.js:1238:24)
I20180507-17:56:11.497(0)?     at Object.task (packages/meteor.js:1251:14)
I20180507-17:56:11.497(0)?     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:869:16)
```
Despite seeing this error it doesn't seem like it prevent's any of the messages from going through so I am not sure of the impact this error is having. I do see this error thrown very often.

If you feel like you cannot resolve either of these without a reproduction let me know and I'll see what I can do to put one together.

**Comment by theodorDiaconu** [comment]
@elm2178 can you recheck please?

**Comment by elm2178** [comment]
Those changes resolved all the errors we were seeing. Have not yet done a more thorough regression test but looks very promising. @theodorDiaconu Would you say this branch is stable enough to test now?

**Comment by theodorDiaconu** [comment]
@elm2178 glad to hear that, what is currently left in here, is to provide more documentation to the code. But it's as good as it gets. I think it's worth to take it out for a spin.

**Comment by theodorDiaconu** [comment]
@nathan-muir thoughts on this ? Would love to get your input. This is a big change and I'm a bit reluctant to merge and release

File: lib/mongo/ObserveMultiplex.js [hunk 1]
```diff
@@ -0,0 +1,289 @@
...
+    },
+    _ready: function() {
+        return this._readyFuture.isResolved();
+    },
+    _applyCallback: function(callbackName, args) {
+        var self = this;
+
+        const isOptimistic = !!OptimisticInvocation.get();
+        // TODO Add a debug message here
+        const runType = isOptimistic ? 'runTask' : 'queueTask';
```
Comment (nathan-muir) [inline lib/mongo/ObserveMultiplex.js]: @theodorDiaconu instead of forcing optimistic invocations to be synchronous, could we try -

given a helper function like:
```js
function maybeBeginWrite(){
  const fence = !!OptimisticInvocation.get() && DDPServer._CurrentWriteFence.get();
  if (fence) {
    return fence.beginWrite();
  } else {
    return {committed: function () {}};
  }
}
```

We can then write:

```
const fence = maybeBeginWrite();

self._queue.queueTask(function(){
   try {
      /* ... */
   } finally {
      fence.committed();
  }
});
```

**Comment by nathan-muir** [comment]
@theodorDiaconu I have been reading the commits as the PR has progressed. 

I think the changes _look_ great, but I'm haven't tried it out yet.

I should be on to a new round of testing once meteor-1.7 is released, and I could try testing this update around the same time.

**Comment by etyp** [comment]
So some updates from our side:

1. We've run full manual regression tests, automated tests, and exploratory tests and our app is **singing** in production. Which is great news :)
2. We're using custom namespaces for 1 collection and even at a smaller concurrent user load (since it's the weekend), we're seeing some performance boost
3. Overall memory usage is down by about 30%
4. Overall cpu usage is also down by about 30%

We're going to continue to monitor through the weekend and will add the Meteor facts package so that (assuming no further issues) we can provide more detailed metrics.

**One issue we're running into:**
We saw this in initial testing and thought we resolved, but some publications are throwing the following:

```
TypeError: Cannot set property '_ownerInfo' of undefined
    at MongoConnection.mongoConnectionProto._observeChanges (packages/hiveteams_hive-apm.js:3093:37)
    at Cursor.observeChanges (packages/mongo/mongo_driver.js:936:22)
    at Cursor.MeteorCursor.observeChanges (packages/peerlibrary_reactive-mongo/server.coffee:37:35)
    at Cursor.cursorProto.(anonymous function) (packages/hiveteams_hive-apm.js:3380:32)
    at Cursor.kadira_Cursor_observeChanges [as observeChanges] (packages/hiveteams_hive-apm.js:3784:41)
    at Function._publishCursor (packages/mongo/collection.js:360:32)
    at Cursor._publishCursor (packages/mongo/mongo_driver.js:899:27)
    at Subscription._publishHandlerResult (packages/ddp-server/livedata_server.js:1087:13)
    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1060:10)
    at Subscription.subscriptionProto._runHandler (packages/hiveteams_hive-apm.js:2814:24)
    at Session._startSubscription (packages/ddp-server/livedata_server.js:859:9)
    at Session.sub (packages/ddp-server/livedata_server.js:625:12)
    at packages/hiveteams_hive-apm.js:2677:34
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at Session.sessionProto.protocol_handlers.sub (packages/hiveteams_hive-apm.js:2676:44)
    at packages/ddp-server/livedata_server.js:559:43
```

The publications throwing the error **do not** use server side autoruns, yet we're seeing the reactive mongo package in the error stack. It's unclear how to reproduce and whether this affects users, but I'm guessing it does.

@theodorDiaconu any idea what might cause this?

**Comment by ramezrafla** [comment]
@etyp 
Concerning your error, do you have reactive:false in any internal queries in your pub? When using autorun server side I remember reading in the package docs that all queries in pubs become reactive

**Comment by etyp** [comment]
@ramezrafla hmm, no not in the pubs that are throwing the errors. One thing to note is that the docs returned in these pubs are also sometimes returned in pubs with autoruns, so it might be mergebox related.

These pubs throwing the errors are actually pretty dead simple, for example:

```
Meteor.publish('driveFile', function driveFile(fileId) {
  check(fileId, String);
  if (!this.userId) throw new Meteor.Error('no-access', 'Must be logged in to access files');

  return MyFiles.find({
    _id: fileId,
    deleted: { $ne: true },
    allowedUsers: this.userId,
  });
});
```

Meanwhile, we have another pub using an autorun that sometimes returns overlapping docs. See sample below (not actual code for sake of brevity):

```
Meteor.publish('itemAttachments', function driveFile(itemId) {
  check(itemId, String);
  if (!this.userId) throw new Meteor.Error('no-access', 'Must be logged in to access attachments');

  this.autorun(() => {
    const item = Items.findOne(itemId); // findOne called here in case permissions change.
    if (item.hasAccess(this.userId)) {
      return MyFiles.find({
        _id: { $in: item.attachments },
        deleted: { $ne: true },
        allowedUsers: this.userId,
      });
    }
    return this.ready();
  });
});
```

**Comment by theodorDiaconu** [comment]
@etyp what does this line do:
```js
TypeError: Cannot set property '_ownerInfo' of undefined
    at MongoConnection.mongoConnectionProto._observeChanges (packages/hiveteams_hive-apm.js:3093:37)
```

**Comment by theodorDiaconu** [comment]
@etyp I am surprised by less memory consumption, it should have been the other way around, and 30% isn't very satisfactory ... something's going on, can you run a cpu profile ?

**Comment by etyp** [comment]
@theodorDiaconu seems like polling and oplog observe drivers set their `_multiplexer` [property in constructor](https://github.com/meteor/meteor/blob/ecf726ebf383917baba929e26adc40bd95281eab/packages/mongo/polling_observe_driver.js#L7). Would it make sense to just do the same on your [observeChanges override](https://github.com/cult-of-coders/redis-oplog/blob/295637efe4b6bc15d6e25865d28f15dd0e52fce1/lib/mongo/observeChanges.js#L139) like:

```
export default function(cursorDescription, ordered, callbacks) {
    var self = this;
    // ... Redacted code here ...
    // Blocks until the initial adds have been sent.
    multiplexer.addHandleAndSendInitialAdds(observeHandle);

    // Set _multiplexer property
    self._multiplexer = multiplexer;

    return observeHandle;
}
```

Not sure if that's solution or a workaround that misses a larger issue.

**Comment by theodorDiaconu** [comment]
@etyp yes you're right, that was missing.

**Comment by etyp** [comment]
Great news re: the APM issue. We'll deploy tonight and confirm if it's working tomorrow.

We're having one final issue which we think is pretty major and related to Redis Oplog. Meteor's `autoupdate` package seems to be [erroring out on subscription](https://github.com/meteor/meteor/blob/devel/packages/autoupdate/autoupdate_client.js#L72). We're seeing this across dozens of users and don't see the error reported anywhere on the server.

On the client, the stack trace on this error looks like:

```
[
autoupdate subscription failed:, 
{
error: 500, 
errorType: Meteor.Error, 
isClientSafe: True, 
message: Internal server error [500], 
name: Error, 
reason: Internal server error, 
stack: 
Error
    at o (https://app.hive.com/20df3fb07fa278b9c7ba9d139c82921f1320b4de.js?meteor_js_resource=true:61:19901)
    at t.e [as _livedata_nosub] (https://app.hive.com/20df3fb07fa278b9c7ba9d139c82921f1320b4de.js?meteor_js_resource=true:61:19974)
    at t.e [as onMessage] (https://app.hive.com/20df3fb07fa278b9c7ba9d139c82921f1320b4de.js?meteor_js_resource=true:61:22956)
    at https://app.hive.com/20df3fb07fa278b9c7ba9d139c82921f1320b4de.js?meteor_js_resource=true:59:3350
    at Array.forEach (<anonymous>)
    at e.t [as forEachCallback] (https://app.hive.com/20df3fb07fa278b9c7ba9d139c82921f1320b4de.js?meteor_js_resource=true:59:4560)
    at x.socket.onmessage (https://app.hive.com/20df3fb07fa278b9c7ba9d139c82921f1320b4de.js?meteor_js_resource=true:59:3312)
    at x.o.dispatchEvent (https://app.hive.com/20df3fb07fa278b9c7ba9d139c82921f1320b4de.js?meteor_js_resource=true:59:7420)
    at x._dispatchMessage (https://app.hive.com/20df3fb07fa278b9c7ba9d139c82921f1320b4de.js?meteor_js_resource=true:59:21171)
    at x._didMessage (https://app.hive.com/20df3fb07fa278b9c7ba9d139c82921f1320b4de.js?meteor_js_resource=true:59:22071)
    at WebSocket.o.ws.onmessage (https://app.hive.com/20df3fb07fa278b9c7ba9d139c82921f1320b4de.js?meteor_js_resource=true:59:24220)
}
]
```

We're thinking it might be related to this error that shows `No callback invoker for method 178` (where 178 can be any number). Sample stack trace:

```
[
Exception in flushing DDP buffered writes:, 
{
message: Expected not to find a document already present for an add, 
name: Error, 
stack: 
Error: Expected not to find a document already present for an add
    at Object.update (https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:69:3697)
    at Object.r.(anonymous function) [as update] (https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:61:7136)
    at https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:61:16523
    at Array.forEach (<anonymous>)
    at https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:61:16501
    at Array.forEach (<anonymous>)
    at t.e [as _performWrites] (https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:61:16448)
    at t.e [as _flushBufferedWrites] (https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:61:16216)
    at https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:1:7874
    at r (https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:13:1576130)
}, 
Error: Expected not to find a document already present for an add
    at Object.update (https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:69:3697)
    at Object.r.(anonymous function) [as update] (https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:61:7136)
    at https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:61:16523
    at Array.forEach (<anonymous>)
    at https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:61:16501
    at Array.forEach (<anonymous>)
    at t.e [as _performWrites] (https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:61:16448)
    at t.e [as _flushBufferedWrites] (https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:61:16216)
    at https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:1:7874
    at r (https://app.hive.com/d4f077e962ff5cc2b25eaff8d77bde07bc857a09.js?meteor_js_resource=true:13:1576130)
]
```

We've tried bringing the [Autoupdate](https://github.com/meteor/meteor/tree/devel/packages/autoupdate) package locally to see if we can reproduce, but have had no such luck. It seems the error is thrown even when a client is loading the latest version of the web app.

Any idea what could be causing the `No callback invoker for method N` or `autoupdate subscription failed` errors?

This issue is pretty severe as users can't load app fully. Unfortunately, we may need to roll back if we can't resolve today 😞

**Comment by theodorDiaconu** [comment]
@etyp is this happening on client or server ?

**Comment by etyp** [comment]
@theodorDiaconu those are on client. Now we have an issue with all servers spiked to 100% cpu on deploy. Constantly seeing the following:

```
TypeError: Cannot read property 'stop' of undefined
    at ObserveMultiplexer.onStop [as _onStop] (packages/cultofcoders:redis-oplog/lib/mongo/observeChanges.js:53:25)
    at ObserveMultiplexer._stop (packages/cultofcoders:redis-oplog/lib/mongo/ObserveMultiplex.js:119:14)
    at ObserveMultiplexer.removeHandle (packages/cultofcoders:redis-oplog/lib/mongo/ObserveMultiplex.js:105:18)
    at ObserveHandle.ObserveMultiplex.js.ObserveHandle.stop (packages/cultofcoders:redis-oplog/lib/mongo/ObserveMultiplex.js:288:23)
    at Subscription.<anonymous> (packages/mongo/collection.js:377:21)
    at runWithEnvironment (packages/meteor.js:1238:24)
    at packages/meteor.js:1251:14
    at packages/ddp-server/livedata_server.js:1155:7
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Subscription._callStopCallbacks (packages/ddp-server/livedata_server.js:1154:7)
    at Subscription._deactivate (packages/ddp-server/livedata_server.js:1144:10)
    at Subscription.subscriptionProto._deactivate (packages/hiveteams_hive-apm.js:2876:24)
    at packages/ddp-server/livedata_server.js:893:11
    at Function._.each._.forEach (packages/underscore.js:147:22)
    at Session._deactivateAllSubscriptions (packages/ddp-server/livedata_server.js:892:7)
    at packages/ddp-server/livedata_server.js:450:12
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at packages/meteor.js:502:25
    at runWithEnvironment (packages/meteor.js:1238:24)
```

We just tried adding the change which sets the `self._multiplexer = multiplexer;` hoping that would resolve it, but no luck ---- things still spiking to 100%.

We are working to revert back to poll and diff for now, but I'll provide an update once our service is back up.

**Comment by etyp** [comment]
Also these errors are firing quite a bit. Sorry for spamming with error logs here, just want to log to see if you have ideas while we try to work through this:

```
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info Exception from sub actions.forView id etSDGLk2Nm8FikCMg Error: Future must resolve before value is ready 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Future.get (/var/app/current/programs/server/node_modules/fibers/future.js:210:10) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Future.wait (/var/app/current/programs/server/node_modules/fibers/future.js:449:15) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Meteor._SynchronousQueue.SQp.runTask (packages/meteor.js:801:7) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at RedisSubscriptionManager.attach (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriptionManager.js:40:20) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at new RedisSubscriber (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriber.js:23:34) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at new RedisOplogObserveDriver (packages/cultofcoders:redis-oplog/lib/mongo/RedisOplogObserveDriver.js:56:28) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at MongoConnection.<anonymous> (packages/cultofcoders:redis-oplog/lib/mongo/observeChanges.js:129:21) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at MongoConnection.MongoInternals.Connection._observeChanges (packages/peerlibrary_reactive-publish/server.coffee:50:35) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at MongoConnection.mongoConnectionProto._observeChanges (packages/hiveteams_hive-apm.js:3077:38) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Cursor.observeChanges (packages/mongo/mongo_driver.js:936:22) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Cursor.MeteorCursor.observeChanges (packages/peerlibrary_reactive-mongo/server.coffee:37:35) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Cursor.cursorProto.(anonymous function) (packages/hiveteams_hive-apm.js:3386:32) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Cursor.kadira_Cursor_observeChanges [as observeChanges] (packages/hiveteams_hive-apm.js:3790:41) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Function._publishCursor (packages/mongo/collection.js:360:32) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Cursor._publishCursor (packages/mongo/mongo_driver.js:899:27) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at packages/ddp-server/livedata_server.js:1118:15 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Array.forEach (<anonymous>) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Function._.each._.forEach (packages/underscore.js:139:11) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Subscription._publishHandlerResult (packages/ddp-server/livedata_server.js:1117:11) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Computation.<anonymous> (packages/peerlibrary_reactive-publish/server.coffee:181:19) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at runWithEnvironment (packages/meteor.js:1238:24) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at packages/meteor.js:1251:14 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at _runInside.computation (packages/peerlibrary_server-autorun/server.coffee:337:16) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at FiberUtils.synchronize (packages/peerlibrary_server-autorun/server.coffee:321:9) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at FiberUtils.synchronize (packages/peerlibrary_fiber-utils/src/server.coffee:56:12) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Computation._runInside (packages/peerlibrary_server-autorun/server.coffee:312:16) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at FiberUtils.synchronize (packages/peerlibrary_server-autorun/server.coffee:331:8) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at FiberUtils.synchronize (packages/peerlibrary_fiber-utils/src/server.coffee:56:12) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Computation._compute (packages/peerlibrary_server-autorun/server.coffee:328:16) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at new Computation (packages/peerlibrary_server-autorun/server.coffee:246:8) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Object.Tracker.autorun (packages/peerlibrary_server-autorun/server.coffee:181:7) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Subscription.publish.autorun (packages/peerlibrary_reactive-publish/server.coffee:167:24) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Subscription.actionsForColumn (imports/api/actions/server/publications.js:219:8) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at packages/matb33_collection-hooks.js:307:21 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Subscription.<anonymous> (packages/matb33_collection-hooks.js:306:28) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Subscription.newFunc (packages/peerlibrary_subscription-data/server.coffee:25:19) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Subscription.newPublishFunction (packages/peerlibrary_reactive-publish/server.coffee:191:30) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Subscription.<anonymous> (imports/startup/server/publish-hooks.js:34:28) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Subscription._handler (imports/startup/server/publish-hooks.js:34:28) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1043:15) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:51) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Subscription.subscriptionProto._runHandler (packages/hiveteams_hive-apm.js:2814:24) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at packages/ddp-server/livedata_server.js:826:41 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Function._.each._.forEach (packages/underscore.js:147:22) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at packages/ddp-server/livedata_server.js:822:9 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Session._setUserId (packages/ddp-server/livedata_server.js:816:34) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at MethodInvocation.setUserId [as _setUserId] (packages/ddp-server/livedata_server.js:677:14) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at MethodInvocation.setUserId (packages/ddp-common/method_invocation.js:92:10) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at AccountsServer.Ap._loginUser (packages/accounts-base/accounts_server.js:306:20) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at AccountsServer.Ap._attemptLogin (packages/accounts-base/accounts_server.js:360:12) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:545:21) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at MethodInvocation.methodMap.(anonymous function) (packages/hiveteams_hive-apm.js:2764:30) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at MethodInvocation.<anonymous> (imports/startup/server/method-hooks.js:39:27) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at MethodInvocation.<anonymous> (imports/startup/server/method-hooks.js:39:27) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Promise (packages/ddp-server/livedata_server.js:715:46) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at new Promise (<anonymous>) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Session.method (packages/ddp-server/livedata_server.js:689:23) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at packages/hiveteams_hive-apm.js:2652:38 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at Session.sessionProto.protocol_handlers.method (packages/hiveteams_hive-apm.js:2651:44) 
May 30 15:56:41 production-i-01a623c5c2c83eda4 default: info         at packages/ddp-server/livedata_server.js:559:43 
```

**Comment by theodorDiaconu** [comment]
I understand. Revert right now and I'll update you on those issues.
I had the same problem with `Error: Future must resolve before value is ready ` 2 days ago, it's time to dig deep in it.

**Comment by theodorDiaconu** [comment]
@etyp I think this last commit fixes it basically I think it's related to having a runTask inside another runTask...

**Comment by etyp** [comment]
@theodorDiaconu thank you! We'll try out the changes and gear up for another round of testing outside of production. Do you have any idea how to reproduce the issue that was happening without these changes?

**Comment by benweissmann** [comment]
I gave this a test in combination with `externalRedisPublisher` and `oplogtoredis`.

Everything looks good! The automated tests pass, and some manual clicking around didn't show any issues.

One possible issue though:

Without redis-oplog, and with the master branch of redis-oplog, the order of messages over the websocket when making a call looks like this:

```
SEND ["{\"msg\":\"method\",\"method\":\"tasks.insert\",\"params\":[\"foo\"],\"id\":\"2\",\"randomSeed\":\"34c61b0a6f6b20c42916\"}"]
RECEIVE ["{\"msg\":\"result\",\"id\":\"2\"}"]
RECEIVE ["{\"msg\":\"added\",\"collection\":\"tasks\",\"id\":\"hhyAhPjGSfXvvMkA6\",\"fields\":{\"text\":\"foo\",\"owner\":\"testuser\",\"username\":\"Test User\"}}"]
RECEIVE ["{\"msg\":\"updated\",\"methods\":[\"2\"]}"]
```

The order here is (method call), (result), (changed documents), (updated)

With this branch of redis-oplog, however, the order is this:

```
SEND ["{\"msg\":\"method\",\"method\":\"tasks.insert\",\"params\":[\"foo\"],\"id\":\"2\",\"randomSeed\":\"34c61b0a6f6b20c42916\"}"]
RECEIVE ["{\"msg\":\"added\",\"collection\":\"tasks\",\"id\":\"hhyAhPjGSfXvvMkA6\",\"fields\":{\"text\":\"foo\",\"owner\":\"testuser\",\"username\":\"Test User\"}}"]
RECEIVE ["{\"msg\":\"updated\",\"methods\":[\"2\"]}"]
RECEIVE ["{\"msg\":\"result\",\"id\":\"2\"}"]
```

The order here is (method call), (changed documents), (updated), (result)

This appears so be valid in DDP ("There is no particular required ordering between `result` and `updated` messages for a method call." from [the spec](https://github.com/meteor/meteor/blob/devel/packages/ddp/DDP.md#remote-procedure-calls), but it something interesting to note and might cause compatibility issues with nonconforming DDP clients that expect to get "result" before "updated".

**Comment by benweissmann** [comment]
Hey @etyp -- the new ordering of messages occurs in all four of those cases. It also happens both in the default configuration of redis-oplog, and with externalRedisPublisher + oplogtoredis.

**Comment by theodorDiaconu** [comment]
@benweissmann that is very strange, with the latest release I have the proper order, with optimistic-ui
```

\"/tasks/update\",\"params\":[{\"_id\":\"Go7nWCm7o3ALe3gY7\"},{\"$set\":{\"priority\":\"high\"}},{}],\"id\":\"6\"}"] | 149 | 12:39:04.988
-- | -- | --
a["{\"msg\":\"changed\",\"collection\":\"tasks\",\"id\":\"Go7nWCm7o3ALe3gY7\",\"fields\":{\"priority\":\"high\",\"updatedAt\":{\"$date\":1528191545009}}}"] | 155 | 12:39:05.049
a["{\"msg\":\"changed\",\"collection\":\"projects\",\"id\":\"mcs5WP4uwfB9rW6mD\",\"fields\":{\"updatedAt\":{\"$date\":1528191545028}}}"] | 136 | 12:39:05.068
a["{\"msg\":\"updated\",\"methods\":[\"6\"]}"] | 46 | 12:39:05.071
a["{\"msg\":\"result\",\"id\":\"6\"}"]


```

**Comment by benweissmann** [comment]
@theodorDiaconu Are you referring to this branch as the "latest release"? Or master? The order of messages you show there is the new order (the one i'm seeing on this branch but not on master or on vanilla Meteor) -- the "result" message is coming after "changed"/"updated" rather than before.

**Comment by theodorDiaconu** [comment]
@benweissmann those things are related to optimistic-ui, didn't you disable it to be able to test oplogtoredis ? This should've been on master as well, but it needs a little bit more care.

**Comment by benweissmann** [comment]
@theodorDiaconu I have been using optimistic UI with oplogtoredis (redis-oplog still does local dispatch of events when externalRedisPublisher is true, so optimistic UI still works -- it just ends up double-processing the changes like it did before we added the deduplication ID).

The different ordering of messages (`result` after `updated`) happens both with externalRedisPublisher+oplogtoredis, as well as with the default configuration (no oplogtoredis)

**Comment by etyp** [comment]
@theodorDiaconu it seems like everything is working for us across the board. Can we consider merging this in for release?

@benweissmann everything still looking good on your side?

@ramezrafla @nathan-muir have either of you had a chance to test this out in production as well?

**Comment by theodorDiaconu** [comment]
@etyp I've also rolled-out this branch in all of the apps. Currently no errors. Waiting another week to fully test this. This change is huge.

**Comment by elm2178** [comment]
@theodorDiaconu any updates on those tests you mentioned above? From the tests on our end, everything still looks good but we want to confirm that no one else has noticed anything strange before taking any next steps.

**Comment by theodorDiaconu** [comment]
@elm2178 @etyp I've seen an increase in speed in all of my apps using this. Nothing strange happened everything is fine on my end.

**Comment by etyp** [comment]
@theodorDiaconu got it. Any idea the root cause of the issue, how we can resolve, or what the timeline to resolve is?

We're really eager to get this merged so we're not alone in having this branch live in production

**Comment by theodorDiaconu** [comment]
@etyp need to do digging for it, I think next week. How's it working so far in production ? :D

**Comment by etyp** [comment]
@theodorDiaconu we moved to our beta release server, which a decent subset of users have access to. So far, so good. We were aiming to release to full production again this weekend but it seems we will need to hold as a redis server going out would be catastrophic :)

Does the issue happen every time redis connection is lost? We can try investigating on our side as well if that's the case.

**Comment by theodorDiaconu** [comment]
@etyp the problem was related to a badly configured redis, since then the issue did not occur.

**Comment by elm2178** [comment]
Hey @theodorDiaconu, we saw this log today after running redis oplog on our servers for just over a week.
```
RedisOplog - Warning - A race condition occurred when running upsert
```

This is the first time we have seen this warning. Is this something we should be concerned about? Also, are there any other log lines we should keep an eye out for?

**Comment by theodorDiaconu** [comment]
@elm2178 yes, there are super super rare scenarios when this can happen. This happens on upsert, and the problem is that one or more documents did not get live updated

**Comment by etyp** [comment]
@theodorDiaconu using the facts package, we get negative values on `observe-drivers-oplog`. I think the incrementing of this value was accidentally missed in this PR.

Is it right to assume that we should call the following at the end of the `RedisOplogObserveDriver` constructor?

```
    Package['facts-base'] &&
      Package['facts-base'].Facts.incrementServerFact(
        'mongo-livedata',
        'observe-drivers-oplog',
        1
      );
```

**Comment by etyp** [comment]
Also, we've had this live in production for nearly 2 months and it's been working well. In fact, it has helped us surface and sort out other issues we were unaware of :)

Is there any plan to merge + publish this soon?

**Comment by theodorDiaconu** [comment]
@etyp yes you can create a new issue. very weird indeed.

**Comment by theodorDiaconu** [comment]
@etyp solved 👍
