### PR TITLE
[RFC] Release 1.2

### LINKED ISSUE #94: Redis Monitor
RedisOplog.monitor(console)

- Number of active queries followed
- Number of re-uses per queries (and give a reusability percentage)
- How much memory is the store ocuppying
- What is the maximum publication that ocuppies most memory (offer the name and id)
- What is the minimum publication that ocuppies the least memory. (name and id)

### LINKED ISSUE #124: Optimistic UI Improvements
Optimistic UI should work much like a synthetic processor.

Optimistic UI should only work with the current observer, not push the changes to all of them.

Refactoring strategy:
We should allow triggering optimistic-ui changes only to the current observer, or somehow use the optimistic UI from Meteor

### LINKED ISSUE #135: Fix limit-sort processing strategy with negative fields
- [ ] Write tests for negative fields processing
- [ ] Write tests for empty fields fields: {}, it should only show _id

### LINKED ISSUE #137: Different behavior with reactive sources
We've recognized a behavior which is different to the normal one with Meteors live data system when we use a reactive source.

We're using ViewModel within our app and defined the following functions:

```
// Reactive source within ViewModel:

profilePicture() {

        if (Meteor.user() && Meteor.user().profile.picture) return "https://files.myapp.com/profile-pictures/" + Meteor.user().profile.picture;

        return null;
    },

// Autoruns
 function () {
            // Sync data with forms
            if (Meteor.user() && Meteor.user().profile) {
                this.gender(Meteor.user().profile.gender);
                this.s_gender(Meteor.user().profile.s_gender);
            }
        },

        function() {
            // Check if ready but user forgot to create a profile picture

            if(this.gender() && this.s_gender() && !this.profilePicture()) {
                this.templateInstance.$(".pp-preview").click();
            }
        }
```

At the same time, we sending a ping to the server every 20 seconds. Now we have the following problem: The last autorun is fired every 20 seconds, when the <code>Meteor.user()</code> object changes (we update the <code>status.lastPing</code> field which is NOT published to the client). So our users will see a modal for taking a profile picture every 20 seconds. This behavior doesn't exists when we deactivate redis-oplog and use the normal live data system of Meteor (dev mode). 

If we remove <code>this.profilePicture()</code> and change the if statement to

```
   if(this.gender() && this.s_gender()) {
                this.templateInstance.$(".pp-preview").click();
    }
```
the modal doesn't show up every 20 seconds. So I try to understand why we have the issue with redis-oplog and not with the normal Meteor system? Is it possible that even unpublished fields will trigger a rerun when using redis-oplog?

### LINKED ISSUE #138: Exception in callback of async function: TypeError: callback is not a function
Hey,
having an issue with using settings like pushToRedis while executing a remove command. We using it server only for a cron job:

    Messages.remove({userId: id}, {pushToRedis: false});

In dev mode this gives me an:

    Exception in callback of async function: TypeError: callback is not a function

On production we get:

    Exception in callback of async function: RangeError: attempt to write outside buffer bounds
     at Object.Future.wait (/var/app/bundle/programs/server/node_modules/fibers/future.js:446:16)

### PR DESCRIPTION
**Pull request by theodorDiaconu**
- Fixed #135
- Fixed #137 
- Fixed #94
- Fixed #138
- Fixed #124 

- [x] fix #138 - when pushToRedis is false don't perform additional computations
- [x] create defaults for mutation config like {pushToRedis: false, optimistic: true}
- [x] solve optimistic ui using the strategy specified in #124 . The idea breaks when publishComposite is in use. It will cause some delays for methods.
- [x] #94 - Create a RedisOplog.stats() function which shows information about current publications, how many observers they have, how much memory it is ocuppying, etc. Should return an object.
- [x] Write custom publish-composite that works with this perfectly.
- [x] add pushToRedis and optimistic as configurable stuff

### CODE REVIEW

File: lib/mongo/lib/compensateForLatency.js [hunk 1]
```diff
@@ -23,5 +23,12 @@ export default (channels, event, uid, doc, fields) => {
                 // }
             })
         }
+
+        let directSubs = RedisSubscriptionManager.store[channel + '::' + doc._id];
+        if (directSubs && directSubs.length) {
+            directSubs.forEach(subscriber => {
```
Comment (theodorDiaconu) [inline lib/mongo/lib/compensateForLatency.js]: don't forget to put channelLastIds until you find a better way for optimistic ui

**Comment by maxnowack** [comment]
Is there a chance to get a way to generally turn on optimistic ui?

**Comment by theodorDiaconu** [comment]
@maxnowack yes, will add it as setting.
